language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.5.7
 
before_install:
 - gem install bundler:2.0.2

script:
 - bundle exec rspec
 - bundle exec rake cucumber

deploy:
  provider: heroku
  api_key: 64e8217c-ea4b-4b37-9581-893996c8fa38
  app: ci-app-tom